[platformio]
default_envs = cyd_st7789_audio_test3

[env:cyd_st7789_audio_test3]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = huge_app.csv
build_src_filter =
  +<main.cpp>
lib_deps =
  bodmer/TFT_eSPI@2.5.43
build_flags =
  -D USER_SETUP_LOADED=1
  -D USE_HSPI_PORT=1
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D ST7789_DRIVER=1
  -D TFT_INVERSION_OFF=1
  -D TFT_RGB_ORDER=0
  -D TFT_SPI_MODE=3
  -D SPI_FREQUENCY=40000000
